# Generated by Django 5.0.6 on 2024-05-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='happy_clients',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='project_completed',
            field=models.IntegerField(max_length=200),
        ),
    ]
