# Generated by Django 5.0.6 on 2024-05-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='happy_clients',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='positive_feedback',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='project_completed',
            field=models.IntegerField(),
        ),
    ]
