# Generated by Django 5.0.6 on 2024-05-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_description_contact_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='photo',
            new_name='image',
        ),
    ]
