# Generated by Django 5.0.6 on 2024-05-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_photo_teammember_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='media/Testimonals')),
                ('designation', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
