# Generated by Django 5.0.6 on 2024-06-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_testimonals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonals',
            options={'verbose_name': 'Testimonal', 'verbose_name_plural': 'Testimonals'},
        ),
    ]
