# Generated by Django 5.0.6 on 2024-06-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_company_address_alter_company_happy_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonals',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testimonals',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testimonals',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
