# Generated by Django 5.0.6 on 2024-06-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_testimonals_company_alter_testimonals_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonals',
            name='image',
            field=models.FileField(default='images/user.jpeg', upload_to='media/Testimonals'),
        ),
    ]
