# Generated by Django 5.0.6 on 2024-06-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_testimonals_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredclient',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='testimonals',
            name='image',
            field=models.FileField(default='user.jpg', upload_to='Testimonals'),
        ),
    ]
